import { EnvironmentRegistry } from "@t3tools/client-runtime/connection";
import { runStream } from "@t3tools/client-runtime/rpc";
import { SpeechSynthesisError, type SpeechSynthesisEvent, WS_METHODS } from "@t3tools/contracts";
import * as Cause from "effect/Cause";
import * as Effect from "effect/Effect";
import * as Exit from "effect/Exit";
import { AtomRegistry } from "effect/reactivity";
import * as Schema from "effect/Schema";
import * as Stream from "effect/Stream";

import { connectionAtomRuntime } from "../connection/runtime";
import { appAtomRegistry } from "../rpc/atomRegistry";
import {
  ReadAloudController,
  type ReadAloudBackend,
  type SpeechGenerationProgress,
} from "./readAloudController";

const isSpeechSynthesisError = Schema.is(SpeechSynthesisError);

function describeProgress(
  event: Extract<SpeechSynthesisEvent, { readonly type: "progress" }>,
): SpeechGenerationProgress {
  const percent = event.total ? Math.round((event.completed / event.total) * 100) : null;
  switch (event.stage) {
    case "downloading-model":
      return { label: "Downloading the speech model on this environment…", percent };
    case "starting":
      return { label: "Starting speech…", percent: null };
    case "generating":
      return {
        label: `Generating speech (${event.completed + 1} of ${event.total ?? "?"})…`,
        percent,
      };
  }
}

/** Speech is generated by the environment's host, which streams one WAV file per sentence. */
const generate: ReadAloudBackend["generate"] = async (request, signal, onProgress, onChunk) => {
  const context = await Effect.runPromise(
    AtomRegistry.getResult(appAtomRegistry, connectionAtomRuntime, { suspendOnWaiting: true }),
  );
  const exit = await Effect.runPromiseExitWith(context)(
    Effect.gen(function* () {
      const registry = yield* EnvironmentRegistry.EnvironmentRegistry;
      yield* registry
        .runStream(
          request.environmentId,
          runStream(WS_METHODS.speechSynthesize, { text: request.text, voice: request.voice }),
        )
        .pipe(
          Stream.runForEach((event) =>
            Effect.sync(() => {
              if (event.type === "chunk") {
                onChunk({
                  blob: new Blob([event.audio.slice()], { type: "audio/wav" }),
                  duration: event.durationSeconds,
                });
              } else {
                onProgress(describeProgress(event));
              }
            }),
          ),
        );
    }),
    { signal },
  );
  if (Exit.isSuccess(exit)) return;
  if (signal.aborted) throw new DOMException("Stopped", "AbortError");
  const error = Cause.squash(exit.cause);
  throw new Error(
    isSpeechSynthesisError(error)
      ? error.message
      : "Couldn't generate speech on this environment. Check that it's connected and up to date.",
  );
};

export const readAloud = new ReadAloudController({
  generate,
  createPlayback: (blob) => {
    const url = URL.createObjectURL(blob);
    const audio = new Audio(url);
    return {
      audio,
      dispose: () => {
        audio.removeAttribute("src");
        audio.load();
        URL.revokeObjectURL(url);
      },
    };
  },
});

if (typeof window !== "undefined") {
  window.addEventListener("pagehide", () => readAloud.stop());
}
if (import.meta.hot) import.meta.hot.dispose(() => readAloud.stop());
